name: Lint
on: push
jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      width:
        node-version: "20"
    - run: npm ci
    - run: npm run lint